-- SQL Schema for Psyche-Architect Database

-- Table: keyword_patterns
CREATE TABLE public.keyword_patterns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern text,
    head_term text,
    status text DEFAULT 'Pending',
    priority integer DEFAULT 1,
    avg_conversion_rate double precision DEFAULT 0.0,
    published_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: data_source
CREATE TABLE public.data_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name text,
    feature1 text,
    feature2 text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: ugc_submissions
CREATE TABLE public.ugc_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_content text,
    hashtag text,
    author text,
    platform text,
    virality_score double precision DEFAULT 0.0,
    status text DEFAULT 'Pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: Please apply this SQL schema to your local Supabase instance manually.
-- You can use the Supabase Studio SQL Editor or the `supabase psql` command.
